// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXTMsESWcJCzDMItxzQhVrPfnQXUDs8RY',
    appId: '1:949064788583:web:9a63685807881b4da4c2c2',
    messagingSenderId: '949064788583',
    projectId: 'sympy-ai',
    authDomain: 'sympy-ai.firebaseapp.com',
    storageBucket: 'sympy-ai.firebasestorage.app',
    measurementId: 'G-SBY8GEKMZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhPlADxL5QW1SHzAexXQeT72qemGU6cyQ',
    appId: '1:949064788583:android:38de1b22aece363ea4c2c2',
    messagingSenderId: '949064788583',
    projectId: 'sympy-ai',
    storageBucket: 'sympy-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhf0bDbzP1IJTkE0vMIajgnwpB0DEeipE',
    appId: '1:949064788583:ios:50b8ef8dd24dcfaca4c2c2',
    messagingSenderId: '949064788583',
    projectId: 'sympy-ai',
    storageBucket: 'sympy-ai.firebasestorage.app',
    iosBundleId: 'com.example.loveable',
  );
}
